```{r purl}
library(knitr)


base.dir<-"C:/ALR/Models/headwaters"


###danger danger
setwd(base.dir)
list.files()
# file.remove("NAMESPACE")
# list.files()
setwd(file.path(base.dir,"r"))
list.files()
# file.remove(list.files())
# list.files()
setwd(file.path(base.dir,"man"))
list.files()
# file.remove(list.files())
# list.files()

dirs<-c("rmd")
while (length(dirs)>0) {
     current.dir<-dirs[1]
     print(paste("=== directory ===", current.dir))
     
     rmd.files<-list.files(include.dirs = F, path = file.path(base.dir,current.dir))[
          grep(x = list.files(include.dirs = F, path = file.path(base.dir,current.dir)),".Rmd")]
     rmd.files<-gsub(".Rmd",replacement = "",x =rmd.files)
#      print(paste("      ",rmd.files))

     for (i in rmd.files){
          print(i)
          purl(paste0(base.dir,"/",current.dir,"/",i,".Rmd"),paste0(base.dir,"/r/",i,".R"))
          }

     dirs<-c(dirs,file.path(current.dir,
                            list.dirs(path = file.path(base.dir,current.dir),recursive = F,full.names = F) 
                            ))
     dirs<-dirs[-1]

}

```

```{r document}
library(devtools)
library(roxygen2)

setwd(base.dir)
document()
```

```{r install and load package}
library(devtools)

setwd(base.dir)
setwd("..")
install("headwaters")
library(headwaters)
```


```{r standard roxygen tags to use}

#' @title 
#' @description
#' @param  \code{}
#' @param  \code{}
#' @param  \code{}
#' @return 
#' @seealso



#' @title Sum of Vector Elements
#' @description
#' \code{sum} returns the sum of all the values present in its arguments.
#'
#' @details
#' @param arg description - a description for each function argument. This can span multiple lines (or even paragraphs) if necessary.
#' @return - the type of object that the function returns

#' @examples - examples of the function in use. 
#' @seealso - to provide pointers to other related topics
#' @references - references to scientific literature on this topic

```







```{r command for loading usgs packages}

# using devtools's install_github() didn't work.  use this command instead

install.packages(c("USGSwsStats"), 
                 repos=c("http://usgs-r.github.com","http://cran.us.r-project.org"),
                 dependencies=TRUE,
                 type="both")
```