```{r purl}
library(knitr)

setwd("C:/ALR/Models/headwaters_base/rmd")
rmd.files<-list.files()[!(paste0("./",list.files()) %in% list.dirs())]
rmd.files

setwd("C:/ALR/Models/headwaters_base")
for (i in rmd.files){
     print(i)
     purl(paste0("./rmd/",i),paste0("./r/",i,".R"))
     }
     # for (i in c("aggregate_date","goodness","utilities","pairs_panels", "retrieve_gages",""))

```

```{r document}
library(devtools)
library(roxygen2)

setwd("C:/ALR/Models/headwaters_base")
document()
```

```{r install and load package}
library(devtools)

setwd("C:/ALR/Models")
install("headwaters_base")
library(headwaters)
```


```{r standard roxygen tags to use}

#' @title 
#' @description
#' @param  \code{}
#' @param  \code{}
#' @param  \code{}
#' @return 
#' @seealso



#' @title Sum of Vector Elements
#' @description
#' \code{sum} returns the sum of all the values present in its arguments.
#'
#' @details
#' @param arg description - a description for each function argument. This can span multiple lines (or even paragraphs) if necessary.
#' @return - the type of object that the function returns

#' @examples - examples of the function in use. 
#' @seealso - to provide pointers to other related topics
#' @references - references to scientific literature on this topic

```


```{r command for loading usgs packages}

# using devtools's install_github() didn't work.  use this command instead

install.packages(c("USGSwsStats"), 
                 repos=c("http://usgs-r.github.com","http://cran.us.r-project.org"),
                 dependencies=TRUE,
                 type="both")
```