```{r}
# q flow
# w weather
# d data of combined flow, weather, and basin stats
# m model
# o model output (calibration fitted values, predictions, goodness of fit)

# oo model output, melted for ggplots
# gg ggplot object


```


```{r create calibration and validation sets}

create.calib <-function( d.records, valid.type="gages.years", 
                              valid.fraction=0.5, seed=NULL, 
                              id.col="site_no", year.col="year",
                              select.gages=NULL, select.years=NULL) {
     
               #      gages.df<-check.args.gages(gages, args.vector=F, 
               #                                args.id.col=gage.id.col, gage.id.class)  
                    #    gage.id.class="character", 
          
     gages <- unique( d.records[,id.col] )
     years <- unique( d.records[,year.col] )
     
     if ( is.null(seed) ) {     
          # randomly generate seed 
          #    but then save that seed, so it's reproducible
          seed<-ceiling(runif(1, min = 1, max = 10^8))
     }
          
     
     if ( !(valid.type %in% c("select.gages", "select.years")) ) {                   
          if ( valid.type == "gages.years" ) {    
               set.seed(seed)
               val.gages<-sample( gages, size=ceiling(length(gages)*(valid.fraction/2)), replace=F )  
               set.seed(seed+1)
               val.years<-sample( years, size=ceiling(length(years)*(valid.fraction/2)), replace=F )  
          }
          else if ( valid.type == "gages" ) {
               set.seed(seed)
               val.gages<-sample( gages, size=ceiling(length(gages)*valid.fraction), replace=F )       
          }
          else if ( valid.type == "year" ) {
               set.seed(seed)
               val.years<-sample( years, size=ceiling(length(years)*valid.fraction), replace=F )            
          }
          
          #select records and return
          valid<-d.records[ d.records[,id.col] %in% val.gages, ]
          valid<-rbind(valid,
                         d.records[ d.records[, year.col] %in% val.years, ])
     
          calib<-d.records[ !(d.records[,id.col] %in% val.gages), ]
          calib<-calib[ !(calib[, year.col ] %in% val.years), ]
     
          sets <- list( calib=calib, valid=valid,
                           seed=seed, val.gages=val.gages, val.years=val.years )
     }
     
     else {
          
          if ( valid.type == "select.gages") {
               #error checking
               if ( is.null(select.gages) )
                    stop( "Must provide list of selected gages" )
               
               calib<-d.records[ !(d.records[,id.col] %in% select.gages), ] #add all records not in selected gages 
               for ( i in 1:length(select.gages) ) {
                    gage.records <- d.records[ d.records[,id.col]==select.gages[i], ]               
                    gage.records <- gage.records[ order(gage.records$date), ]

                    calib<-rbind(calib,
                                 gage.records[ 1:floor(nrow(gage.records)*valid.fraction), ] ) #add 1st 1/2 of years to calib set

                    valid.temp<-gage.records[ (floor(nrow(gage.records)*valid.fraction)+1):nrow(gage.records), ] #add 2nd half of year to valid set
                    if ( i==1 )
                         valid<-valid.temp
                    else
                         valid<-rbind( valid, valid.temp )
               }
               sets <- list( calib=calib, valid=valid, select.gages=select.gages )
                         
          }
          else if ( valid.type == "select.years") {
               print("not written yet...")
          }
     } 


     return( sets )
}

```



```{r calculate goodness of fit statistics}
goodness<-function( obs.real=NULL, pred.log=NULL, bias.correction=NULL ) {

     residuals <- pred.log - log(obs.real)
     pred.real <- retransform( pred.log, residuals=residuals, bias.correction=bias.correction )
#      corr.factor <- mean( exp( pred.real-obs.real ) )
#      pred.corr <- pred.real*corr.factor
     
     f <- data.frame(sample.n=length(obs.real),mean=mean(obs.real))
     f$NSEff.real <- NSeff( obs.real, pred.real )
#      f$NSEff.corr <- NSeff( obs.real, pred.corr )
     f$NSEff.log <- NSeff( log(obs.real), pred.log )
     
     f$bias<-mean(pred.real)-mean(obs.real)
     f$percent.bias<-(mean(pred.real)-mean(obs.real))/mean(obs.real)*100
#      f$percent.bias<-mean( (pred.real-obs.real)/(obs.real) )*100
     f$bias.log<-mean(pred.log)-mean(log(obs.real))
     
#      f$bias.corr<-mean(pred.corr)-mean(obs.real)
#      f$percent.bias.corr<-(mean(pred.corr)-mean(obs.real))/mean(obs.real)*100
     
     f$pearsonR <- cor( obs.real, pred.real, method="pearson" )
#      f$pearsonR.corr <- cor( obs.real, pred.corr, method="pearson" )
     
     f$CV.error <- sd(pred.real-obs.real) / mean(obs.real)
#      f$CV.error.corr <- sd(pred.corr-obs.real) / mean(obs.real)
#      f$corr.factor<-corr.factor
     return(round(f,3))
}
```


```{r run cross validation of model}
cross.val<-function( d.records, model.list, iter=10, valid.fraction=0.5, dep.var="flow.mean", seed=NULL, bias.correction=NULL ) {
     
     #replace this w/ create template function
     
     #goodness cols, plus "melt-like" rows
                                        # period (season)
                                        # valid/calib
                                        # iteration
                                        # 10*4*2, 80 rows 
     
     
#      seasons=c("winter","spring","summer","fall") 
     
     periods <- names(model.list)
     o.goodness<-NULL
     
     if (is.null(seed))
          seed <- ceiling( runif(n=1, max = 10^9, min=1) )
     set.seed(seed)         
     seed.list <- ceiling(runif(iter,max=10^9))
     
     for ( i in 1:iter ) {
#           print(paste("iteration",i))
          
          sets <- create.calib( d.records, valid.type="gages.years", 
                                valid.fraction=0.5, seed=seed.list[i] )

          
          model.list.iter<-model.list
          for ( j in 1:length(periods) ) {
               c <- subset(sets$calib, season==periods[j])
               v <- subset(sets$valid, season==periods[j])
               model.list.iter[[j]] <- update( model.list.iter[[j]], data=c )
               o.goodness.temp <- data.frame(
                                   goodness( obs.real=c[, dep.var], 
                                        pred.log= predict(  model.list.iter[[j]], newdata=c ), 
                                        bias.correction=bias.correction ),
                                   season=periods[j], set="calib", iter=i,
                                   stringsAsFactors=F )
               pred <- predict(  model.list.iter[[j]], newdata=v )
               o.goodness.temp[2,] <- c( as.vector(goodness( obs.real=v[, dep.var], pred.log=pred, bias.correction=bias.correction )),
                                periods[j], "valid", i )
#              
               if( is.null(o.goodness) )
                    o.goodness<-o.goodness.temp
               else 
                    o.goodness <- rbind( o.goodness, o.goodness.temp )
          }
          
          
          
     } #end iterations, i loop     

     return( list(values=o.goodness, seed=seed) )
}
```


```{r goodness of fit boxplots}

goodness.boxplot<-function( o.goodness, measure.vars=c("NSEff.real", "NSEff.log", "bias", "percent.bias"), period.name="season" ) {
     o.goodness[,"period.name"]<-o.goodness[,period.name]
     oo.goodness<-melt( o.goodness, measure.vars=measure.vars )

     gg.goodness<-ggplot( data=oo.goodness, aes(x=eval(period.name), y=value, fill=set) ) + 
          geom_abline(intercept=0, slope=0,col="grey50", lty=2) + 
          scale_fill_manual(values = c("darkred","dodgerblue3")) + theme_bw()
     gg.goodness + geom_boxplot(color="grey20") + facet_wrap(~variable, nrow=2, scales="free_y")

}
```


