

```{r}
#' @title col names for weather input data
#' @description col names for mauer weather data.  original inputs do not have column headers
#columns from mauer
# no export

create.cols.mauer<-function() {
     cols.mauer<-c("year", "month", "day","precip.mm", "tmax","tmin","wind")
     return(cols.mauer)
}

```

```{r}
#' @title Create template of dates in mauer weather data
#' @description mauer dates
# no export

create.template.weather<-function(mauer.dir="C:/ALR/Data/ClimateData/Mauer/daily/east") {
     #***take a look at this later. i can't remember why this is necessary, instead of just using create.template.mauer
     #maybe replace later
     
     cols.mauer<-create.cols.mauer()
     
     setwd(mauer.dir)
# 
     #get dimensions for 3-d array, date, and calculate month/season/annual date columns
     template.weather<-read.table(file=list.files()[1],col.names=cols.mauer)
     
     template.weather$date<-apply(template.weather[,1:3],MARGIN=1,FUN=function(d) (paste(d,collapse="-")))
     template.weather$date<-as.Date(template.weather$date)
     
     #eventually change this to automatically retrieve periods, fetch functions that assign date for that period, and assign date
     template.weather$daily<-as.character(template.weather$date)
     template.weather$monthly<-as.character( to.month(template.weather$date) )
     template.weather$seasonal<-as.character( to.season(template.weather$date) )
     template.weather$annual<-as.character( to.water.year(template.weather$date) )

     period.names<-create.template.periods()$name
     template.weather<-template.weather[,c("date",period.names)]
     
     return(template.weather)
}

```


```{r}
#precip_mm  tmax  tmin
create.cols.weather<-function() {
     cols.weather<-c("precip.total","precip.e","precip.e.lag1","precip.e.lag2","precip.e.lag3",
                     "tmin","tmax","tavg",
                     "pet","pet.lag1","pet.lag2","gdd","gdd.lag1","gdd.lag2",
                     "frozen","melt.doy","melt.doy.lag1","melt.doy.lag2")
#      cols.weather<-c("precip.mm","rain","melt","precip.e","precip.e.lag1","precip.e.lag2","precip.e.lag3",
#                      "tmin","tmax","tavg","pet","gdd","frozen","melt.doy")
     return(cols.weather)
}

```




```{r}
#' @title Create monster list of 3d weather matrices
#' @description used to store aggregated weather metrics
# no export

create.w.matrices<-function( weather.filenames, periods=c("daily", "monthly", "seasonal", "annual") ) {
                                                                 #template.date=NULL
#      if (!("weather.filename" %in% names(gages.spatial)))
#           stop("Must provide gages.spatial object that has been assigned weather.filename")
#      
#      if (is.null(template.date))
     template.date<-create.template.date()
     template.period<-create.template.periods()
     cols.weather<-create.cols.weather()
     
     w.matrices<-list()
     for ( j in template.period$name ) {
          if ( j %in% periods ) {
               w.matrices[[j]]<-array(dim=c(  nrow(template.date[[j]]), 
                                         length(weather.filenames), 
                                         length(cols.weather))  ) 
               dimnames(   w.matrices[[j]]   )[[1]]<-template.date[[j]][,1]
               dimnames(   w.matrices[[j]]    )[[2]]<-weather.filenames
               dimnames(   w.matrices[[j]]   )[[3]]<-cols.weather
          }
          else 
               w.matrices[[j]] <- NA
     }
          
#      for (j in periods) {
# #           print(j)
#           i<-which(template.period$name==j)
#           w.matrices[[i]]<-array(dim=c(  nrow(template.date[[j]]), 
#                                          length(weather.filenames), 
#                                          length(cols.weather))  ) 
#           dimnames(   w.matrices[[i]]   )[[1]]<-template.date[[j]][,1]
#           dimnames(   w.matrices[[i]]    )[[2]]<-weather.filenames
#           dimnames(   w.matrices[[i]]   )[[3]]<-cols.weather
#      }
#      names(w.matrices)<-template.period$name
     return(w.matrices)
}



```
