```{r goodness of fit/validation functions}
#' @title Calculate coefficient of variation of error
#' @description Calculates CV of error, given 2 vectors of observed and predicted values
#' @param obs \code{numeric vector} observed values
#' @param pred \code{numeric vector} predicted values (vector of same length as observed values)
#' @return \code{numeric}
#' @keywords cv, goodness of fit
#' @seealso goodness
#' @export

cv.error<-function(obs,pred) {
     sd(pred-obs)/mean(obs)
}
```




```{r}
#' @title Calculate model bias
#' @description Calculates model bias, given 2 vectors of observed and predicted values
#' @param obs \code{numeric vector} observed values
#' @param pred \code{numeric vector} predicted values (vector of same length as observed values)
#' @return \code{list}
#' @keywords bias, goodness of fit
#' @seealso goodness
#' @export
bias<-function(obs,pred) {
     b<-mean(pred)-mean(obs)
     return(list(bias=b,percent.bias=b/mean(obs)*100))
}
```



```{r}
#' @title Some goodness of fit, validation metrics 
#' @description Calculates and prints a variety of goodness of fit, validation metrics, including rmse, NS eff, bias, percent bias, pearson's R, and cv of error
#' @param obs \code{numeric vector} observed values
#' @param pred \code{numeric vector} predicted values (vector of same length as observed values)
#' @return \code{data.frame}
#' @keywords bias, goodness of fit
#' @seealso bias, cv.error
#' @export

goodness<-function(df=NULL,obs=NULL,pred=NULL) {
     if(is.null(obs) | is.null(pred)){
          if(is.null(df)){
               print("ERROR: must define obs and pred vectors, 
                     or data frame w/ obs and pred columns")
               return(NULL)
          }
          else{
               obs<-df$obs
               pred<-df$pred
          }
     }
     f<-data.frame(sample.n=length(obs),mean=mean(obs))
     f$RMSE<-rmse(obs,pred)
     f$NSEff<-NSeff(obs,pred)
     f$bias<-mean(pred)-mean(obs)
     f$percent.bias<-(mean(pred)-mean(obs))/mean(obs)*100
     f$pearsonR<-cor(obs,pred,method="pearson")
     f$CV.error<-sd(pred-obs)/mean(obs)
     return(round(f,3))
}

```