```{r get gages flow and agg}
library(waterData) #usgs nwis data retrieval
library(ggplot2)
library(plyr)
library(reshape2)
library(lubridate) #some date/time functions
library(zoo)

flow_data_dir<-"C:/ALR/Models_processed_data/flow_timeseries"
setwd(flow_data_dir)

# data_dir<-"C:/ALR/Data"
```


```{r this script s end results}

# setwd(flow_data_dir)
# 
# # gage-related
# load("date_template.Rdata")
# # date_template.Rdata                date.template, complete.cutoff
# # flow_retrieval_template.Rdata      containing qmatrix.names, gages, gages.all, gages.med, gages.small
# 
# # others, basic info on gage retrieval
# # "flow_retrieval_log.txt" 
# # "gages_site_no.txt"
# 
# 
# flow timeseries
# 
# 
# load("qannual.Rdata")
# load("qdaily.Rdata")
# load("qmonthly.Rdata")
# load("qseasonal.Rdata")
# 
# 
setwd(flow_data_dir)
# load(gages.small)
   

```


```{r}
2# #get gage info, sites w/ daily flow
#              (select by list of states, because something is 
#                weird w/ hydr unit codes in nw vt)
#states included: CT, ME, MA, NH, NY, RI, VT
gage_info_url<-"http://nwis.waterdata.usgs.gov/nwis/dvstat?referred_module=sw&state_cd=ct&state_cd=me&state_cd=ma&state_cd=nh&state_cd=ny&state_cd=ri&state_cd=vt&site_tp_cd=OC&site_tp_cd=OC-CO&site_tp_cd=ES&site_tp_cd=LK&site_tp_cd=ST&site_tp_cd=ST-CA&site_tp_cd=ST-DCH&site_tp_cd=ST-TS&index_pmcode_00060=1&group_key=NONE&format=sitefile_output&sitefile_output_format=rdb&column_name=agency_cd&column_name=site_no&column_name=station_nm&column_name=dec_lat_va&column_name=dec_long_va&column_name=dec_coord_datum_cd&column_name=huc_cd&column_name=drain_area_va&column_name=sv_begin_date&column_name=sv_end_date&column_name=sv_count_nu&list_of_search_criteria=state_cd%2Csite_tp_cd%2Crealtime_parameter_selection"

setwd(flow_data_dir)
system(paste("wget -O ./raw_gage_info.txt",gage_info_url) )

#remove extra header 
raw<-readLines("raw_gage_info.txt")
line<-max(grep("agency_cd",raw))
clean<-raw[c(line,(line+2):length(raw))]
# file.remove("raw_gage_info.txt")

#save metadata as file
writeLines(raw[1:(line-1)],"gages_meta.txt")
# [13] "#  agency_cd       -- Agency"                                              
# [14] "#  site_no         -- Site identification number"                          
# [15] "#  station_nm      -- Site name"                                           
# [16] "#  dec_lat_va      -- Decimal latitude"                                    
# [17] "#  dec_long_va     -- Decimal longitude"                                   
# [18] "#  coord_acy_cd    -- Latitude-longitude accuracy"                         
# [19] "#  dec_coord_datum_cd -- Decimal Latitude-longitude datum"                 
# [20] "#  huc_cd          -- Hydrologic unit code"                                
# [21] "#  drain_area_va   -- Drainage area"                                       
# [22] "#  sv_begin_date   -- Site-visit data begin date"                          
# [23] "#  sv_end_date     -- Site-visit data end date"                            
# [24] "#  sv_count_nu     -- Site-visit data count"

#change from raw "lines" to table
gages.all<-read.table(text=clean,header=T,sep="\t",fill=T,
                  colClasses=c("site_no"="character","huc_cd"="character",
                               "sv_begin_date"="Date", "sv_end_date"="Date"))
# rm(gage_info_url,raw,line,clean)

#make sure all gage info has ID
sum(is.na(gages.all$site_no))
sum(is.na(gages.all$dec_lat_va))
sum(is.na(gages.all$dec_long_va))

gages.all<-subset(gages.all,
                  subset=(!is.na(gages.all$site_no) & !is.na(gages.all$dec_lat_va) & !is.na(gages.all$dec_long_va) ))

#convert to sq km, and filter by size
gages.all$da_sqkm<-gages.all$drain_area_va*2.58999
gages.small<-subset(x=gages.all,gages.all$da_sqkm<=50)
gages.med<-subset(x=gages.all,(gages.all$da_sqkm>50 & gages.all$da_sqkm<=100))

#number gages selected 
nrow(gages.all)
nrow(gages.med)
nrow(gages.small)
head(gages.small)

#use gages small
gages<-gages.small

setwd(flow_data_dir)
save(gages.all,gages.med,gages.small,file = "selected.gages.rdata")
```


```{r set up flow metrics data frames}
            
# set up data frames
#(using flow data since 1950 only, even though there are some records back to the 30s, because Mauer met data only available starting 1950)



#create sequences of dates
date.template<-list(      date=data.frame(date=as.character(
                              seq(as.Date("1949/1/1"), as.Date("2010/12/31"), "days")),stringsAsFactors=F),
                          month.date=data.frame(month.date=as.character(
                               seq(as.Date("1949/1/1"), as.Date("2010/12/1"), "months")),stringsAsFactors=F),  
                               #first date of month
                          season.date=data.frame(season.date=as.character(
                               seq(as.Date("1949/02/28"), as.Date("2011/2/28"), "3 month")),stringsAsFactors=F), 
#                                seq(as.Date("1949/05/28"), as.Date("2010/11/28"), "3 month")),stringsAsFactors=F),  should start in may, change next time run
                               #LAST date of season (so the year of winter is the same as following spring)
                          annual.date=data.frame(annual.date=as.character(
                               seq(as.Date("1949/09/30"), as.Date("2011/9/30"), "years")),stringsAsFactors=F)  ) 
                               #LAST date of year 
                               #(so the date of oct-dec months is the same as following jan-sept months)

head(date.template[[3]])

#names of 3 dimensional matrices
qmatrix.names<-c("qdaily",  "qmonthly",   "qseasonal",    "qannual")
gages.small[,qmatrix.names]<-0
# names(date.template)
#                "date"     "month.date"  "season.date"   "annual.date"
# number of records required for daily/monthly/seasonal/or annual to be considered "complete"
complete.cutoff<-c(1,25,80,345)

save(date.template,complete.cutoff,file="date_template.Rdata")
save(qmatrix.names,gages,gages.all,gages.med,gages.small,file="flow_retrieval_template.Rdata")


#create all four matrices
qmatrices<-list(length=4)
for (k in 1:length(qmatrix.names)) {
     print(qmatrix.names[k])
     qmatrices[k][[1]]<-array(dim=c(   nrow(date.template[names(date.template)[k]][[1]]), 
                                       length(gages$site_no), 
                                       5)  ) 
     dimnames(   qmatrices[k][[1]]   )[[1]]<-date.template[names(date.template)[k]][[1]][,1]
     dimnames(   qmatrices[k][[1]]    )[[2]]<-gages$site_no
     dimnames(   qmatrices[k][[1]]   )[[3]]<-c("mean","max","min","low","records")
     names(qmatrices)[k]<-qmatrix.names[k]
}


```

```{r functions to label each daily records with date representing season/month/year}
to.season<-function(d,return.type="date") {           #,out.fmt="seasons"
     x<-data.frame(date=d,year=year(d),month=month(d))  # ,season=time2season(d,out.fmt=out.fmt))  
     
     x[x$month>=12,"year"]<-x[x$month>=12,"year"]+1
#      x$season.num<-sapply(x$season, function(x) {if(x=="autumn") 1
#                                                  else if (x=="winter") 2
#                                                  else if (x=="spring") 3
#                                                  else if (x=="summer") 4 })
     x[,c("season.date","season")]<-matrix(unlist(
          lapply(x$month, function(y) {
               if(y %in% 9:11) c("11/28","fall")
               else if (y %in% c(12,1:2)) c("2/28","winter")
               else if (y %in% 3:5) c("5/28","spring") 
               else if (y %in% 6:8) c("8/28","summer")})),ncol=2,byrow=T)
     x$season.date<-as.Date(paste0(x$year,"/",x$season.date))
     if (return.type=="date")
          return(x[,"season.date"])  
     else if (return.type=="season")
          return(x[,"season"])  
     else
          return(as.data.frame(x[,c("season","season.date","year")]) )  
}
to.water.year<-function(d,date.only=T) {
     x<-data.frame(date=d,year=year(d),month=month(d))
     x[x$month>=10,"year"]<-x[x$month>=10,"year"]+1
     x$water.date<-as.Date(paste0(x$year,"/9/30"))
     if (!date.only)
          return(as.data.frame(x[,c("year","water.date")]))
     else
          return(x[,"water.date"])
}
to.month<-function(d) {
     return(month.date<-as.Date(paste0(year(d),"/",month(d),"/1")))
}

```

```{r aggregate function to use w/ ddply to aggregate}

agg.function<-function(df) return(c(mean=mean(df$val,na.rm=T),
                                    max=max(df$val,na.rm=T),
                                    min=min(df$val,na.rm=T),
                                    low=min(df$rolling7,na.rm=T),
                                    complete=sum(!is.na(df$val))>=cutoff,
                                    records=sum(!is.na(df$val)) ))

```

```{r import and aggregate into flow metrics}


setwd(flow_data_dir)

missing<-c()
# for (i in 1:15)     {
for (i in 1:length(gages$site_no))     {
     print(i)
     flag<-F
     #read flow data
     tryCatch(
          x.all<-importDVs(gages$site_no[i], code = "00060", stat = "00003"),
          error = function(e) {
               missing<-c(missing,i)
               print(paste("ERROR CAUGHT------ station_id:",gages$site_no[i]))
               print(e)
               flag<-T
          })


     if (!flag)
     {                              
          # uses waterData package functions to pull NWIS data from USGS web services 
                                        #  flow/discharge cfs, code 00060
                                        #  daily mean, code 00003
          x.all<-cleanUp(x.all,task="fix",replace=NA)
          print(paste0("     site id: ",gages$site_no[i],";   ",nrow(x.all)," rows"))
          if ( sum(duplicated(x.all$dates)) ) {
               print(x.all[(which(duplicated(x.all$dates))-1):which(duplicated(x.all$dates)),])
               x.all<-x.all[!duplicated(x.all$dates),]
          }
          
          #7 day rolling mean
          x.zoo<-zoo(x.all$val,x.all$dates) 
               #convert to zoo timeseries, pull only values, b/c rollapply works better that way
          rolling7<-rollapply(data = x.zoo,width = 7,
                              FUN = function(x) mean(x), align="left", 
                              partial = TRUE) 
               #7 day rolling average
#                View(x.zoo[1101:2000,])
#                View(rolling7[1101:2000,])
#           x.zoo<-zoo(x.all[,c("val","dates")],x.all$dates) 
               #reconvert to zoo timeseries pulling all columns
          x.zoo<-merge(x.zoo, rolling7)
          x.roll<-as.data.frame(x.zoo)
          names(x.roll)<-c("val","rolling7")
          x.roll$dates<-as.Date(row.names(x.roll))
#           x.roll$dates<-as.Date(row.names(x.roll))
#           x.roll$val<-as.numeric(x.roll$val)
#           x.roll$rolling7<-as.numeric(x.roll$rolling7)
          
#           row.names(x.roll)<-as.character(x.roll$dates)     
          x.roll[,"date"]<-as.character( x.roll$dates )
          x.roll[,"month.date"]<-as.character( to.month(x.roll$dates) )
          x.roll[,"season.date"]<-as.character( to.season(x.roll$dates) )
          x.roll[,"annual.date"]<-as.character( to.water.year(x.roll$dates) )
     
     
     
          for (j in 1:length(qmatrices) ){     
               cutoff<-complete.cutoff[j]     
               x.agg<-ddply(x.roll, names(date.template)[j], agg.function)
               x.agg[x.agg$complete==0,c("mean", "max", "low")]<-NA
               #save a count of # complete records in gages data frame
               gages.small[i,qmatrix.names[j]]<-sum(x.agg$complete)
               
               x.merge<-merge(date.template[j][[1]],x.agg,
                              by=names(date.template)[j],all.x=T,all.y=F)
               qmatrices[[j]][,gages$site_no[i],"mean"]<-x.merge$mean
               qmatrices[[j]][,gages$site_no[i],"max"]<-x.merge$max
               qmatrices[[j]][,gages$site_no[i],"min"]<-x.merge$min
               qmatrices[[j]][,gages$site_no[i],"low"]<-x.merge$low
               qmatrices[[j]][,gages$site_no[i],"records"]<-x.merge$records
          }
     }


}
```



```{r save flow data retrieval log}
setwd(flow_data_dir)

log<-c("flow data retrieval log", format.Date(now()),"\r")
{
if (length(missing)>0) {
     log<-c(log,             
          paste(length(gages$site_no[-missing]),"sites"),
          paste(length(missing),"gages missing data, ignored"),
          "\r","\r",
          "gages missing all data",
          gages$site_no[missing],
          "\r","\r",
          "gages used",
          gages$site_no[-missing])
     write.table(gages$site_no[missing],sep="/r",file="gages_missing_all_data.txt")
     write.table(gages$site_no[-missing],sep="\r",file="gages_site_no.txt",row.names=F,col.names=F)
     }

else {
     log<-c(log,             
          paste(length(gages$site_no),"sites"),
          "\r","\r",
          "sites",
          gages$site_no)
     write.table(gages$site_no,sep="\r",file="gages_site_no.txt",row.names=F,col.names=F)
     }

}
writeLines(log,"flow_retrieval_log.txt")
```




```{r save rdata}
setwd(flow_data_dir)



save(qmatrices,file="flow_matrices.Rdata")


#forgive me.... copy/paste
qdaily<-qmatrices["qdaily"][[1]]
save(qdaily,file=paste0("qdaily.Rdata"))
qmonthly<-qmatrices["qmonthly"][[1]]
save(qmonthly,file=paste0("qmonthly.Rdata"))
qseasonal<-qmatrices["qseasonal"][[1]]
save(qseasonal,file=paste0("qseasonal.Rdata"))
qannual<-qmatrices["qannual"][[1]]
save(qannual,file=paste0("qannual.Rdata"))

# rm(qmatrices,qdaily)
# gc()

```



```{r remove extraneous variables}
rm(clean,cutoff,line,raw,x.all,x.agg,x.merge)
rm(qmatrices)
gc()

```


```{r}
# for (i in 1:length(gages$site_no)) {
#      for (j in 1:length(qmatrices)) {
#           count<-sum(qmatrices[j][[1]][,i,2]>=complete.cutoff[j],na.rm=T)
#           gages[i,qmatrix.names[j]]<-count
#      }
# }

for (i in 1:length(gages$site_no)) {
          count<-sum(qseasonal[,i,2]>=complete.cutoff[3],na.rm=T)
          gages[i,"qseasonal"]<-count
#           count<-sum(qannual[,i,2]>=complete.cutoff[4],na.rm=T)
#           gages[i,"qannual"]<-count
}

```


```{r temp for presentations}
# setwd("C:/ALR/Posters, maps, presentations/EWRI 2014/talk 1 plots and maps")
# gages.temp<-gages[,c("site_no","qseasonal","qannual")]
# gages.temp$site_no<-as.numeric(gages.temp$site_no)
# gages.temp2<-merge(gages.plotted,gages.temp,by="site_no")
# nrow(gages.plotted)
# nrow(gages.temp)
# nrow(gages.temp2)
# head(gages.temp2)
# gages.temp3<-subset(gages.temp2,small_barriers==0)
# nrow(gages.temp3)
# 
# gages.temp4<-SpatialPointsDataFrame(coords=as.matrix(gages.temp3[,c("dec_long_va","dec_lat_va")]), 
#                       data=gages.temp3,
#                       proj4string=CRS(proj4.NHD),
#                       match.ID=F)
# plot(gages.temp4)
# writeOGR(gages.temp4,  ".", layer="gages", driver="ESRI Shapefile")
# write.csv(gages.temp3,"gages.csv",row.names=F)
```



```{r}
# head(x.all)
# sum(!is.na(x.all$date))
# length(unique(x.all$date))
# x.all$date[duplicated(x.all$date)]
# View(x.all[year(x.all$dates)==2013,])
# 
# 
# j<-3
# tail(qmatrices[j][[1]][,1:20,1])
# tail(qmatrices[j][[1]][,1:20,2])
# 
# View(qmatrices[3][[1]][,1:20,1])
```







